<?php

namespace Wheregroup\MapExport\CoreBundle\Entity\PDFElements;


use Wheregroup\MapExport\CoreBundle\Entity\PDFElement;

class Date extends PDFElement
{
    protected function init()
    {
        //$this->getStyle($this->data['template']);

    }

    protected function getStyle()
    {
        //TODO get stile with new ODG parser
    }

    public function draw()
    {
        $this->pdf->SetFont('Arial');
        $this->pdf->Text($this->x, $this->y, date('d.m.Y'));

        //parent::draw(); // TODO: Change the autogenerated stub
    }
}