<?php

namespace Wheregroup\MapExport\CoreBundle\Entity\PDFElements;

use Wheregroup\MapExport\CoreBundle\Entity\PDFElement;

class Scale extends PDFElement
{
    protected $scale;

    protected function init()
    {
        //$this->getStyle($this->data['template']);
        $this->scale = $this->data['scale_select'];

    }

    protected function getStyle()
    {
        //TODO get style with new ODG parser
    }

    public function draw()
    {
        $this->pdf->SetFont('Arial');
        $this->pdf->Text($this->x, $this->y, '1:'.$this->scale);

        //parent::draw(); // TODO: Change the autogenerated stub
    }
}